export default {
  Background: '#FFF',
  BackgroundDark: '#D1D1D1',
  Statusbar: 'light-content',
  HighLight: "#6D88D6",
  Border: '#ebebeb',
  Text: '#4A4A4A',
  Icon: '#4A4A4A',
  AppColor: "#0090FF",
  LoadingColor: '#6D88D6',
  AppColorDark: "#ebebeb",
  AppBarColor: '#09D1FB',
  ProgressColor: 'white',
  darkgray : "#a9a9a9",
  lightgray : "#d3d3d3",
  tabNaviColor: "#b7c900",
  tabNaviItemColor: "#666",
  tabNaviItemActiveColor: "#515C6F", //update color,
  headerText: '#F09D41',
  inputBorder: '#F1F1F1',
  blockedInput: '#ebebeb',
  buttonBackground: "#6D88D6",
  buttonHighlightBackground: "#2CC45A",
  buttonText: "#fff", //update color,
  hyperLinkText: '#515C6F',
  switchNormal: '#CCC',
  switchActive: '#b7c900',
  text: '#515C6F',
  Green: '#0AB431',
  ToolBarText: "white",
}
