export const GET_PRODUCTS_PENDING = "GET_PRODUCTS_PENDING"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL"

export const DO_LIKE_PRODUCT_PENDING = "DO_LIKE_PRODUCT_PENDING"
export const DO_LIKE_PRODUCT_SUCCESS = "DO_LIKE_PRODUCT_SUCCESS"
export const DO_LIKE_PRODUCT_FAIL = "DO_LIKE_PRODUCT_FAIL"

export const DO_UNLIKE_PRODUCT_PENDING = "DO_UNLIKE_PRODUCT_PENDING"
export const DO_UNLIKE_PRODUCT_SUCCESS = "DO_UNLIKE_PRODUCT_SUCCESS"
export const DO_UNLIKE_PRODUCT_FAIL = "DO_UNLIKE_PRODUCT_FAIL"

export const GET_LIKED_PRODUCTS_PENDING = "GET_LIKED_PRODUCTS_PENDING"
export const GET_LIKED_PRODUCTS_SUCCESS = "GET_LIKED_PRODUCTS_SUCCESS"
export const GET_LIKED_PRODUCTS_FAIL = "GET_LIKED_PRODUCTS_FAIL"

export const GET_HOME_PRODUCTS_PENDING = "GET_HOME_PRODUCTS_PENDING"
export const GET_HOME_PRODUCTS_SUCCESS = "GET_HOME_PRODUCTS_SUCCESS"
export const GET_HOME_PRODUCTS_FAIL = "GET_HOME_PRODUCTS_FAIL"